### PR TITLE
Add support for CSS Modules

### PR DESCRIPTION
**Pull request by faergeek**
It's based off another PR right now, I hope you'll accept it before this one and I'll just rebase it :-)

### CODE REVIEW

**Comment by davidguttman** [comment]
Merged the other one, but might want to get some new tests going before putting this one in.

**Comment by faergeek** [comment]
Take a look please

**Comment by faergeek** [comment]
I have no idea how to report error with `through`. Why don't you use `through2`?

**Comment by davidguttman** [comment]
Pretty sure this predates `through2`, happy to switch.

**Comment by davidguttman** [comment]
Tests are passing, looks good to me =)

**Comment by faergeek** [comment]
There are minimal tests for the browser. I think it's enough to test generated source.

**Comment by davidguttman** [comment]
`cssify@1.0.0` =)

**Comment by faergeek** [comment]
Cool :+1:

Could you please take a look at this?
https://github.com/asbjornenge/stylusify/issues/2

I think it would be convenient to use some option for `sassify` transform to compose with cssify and may be something in between, what do you think?

**Comment by davidguttman** [comment]
If I understand correctly, sassify would no longer depend on cssify, but
would just output css. Then the user could have anything after it (but most
likely cssify). Is that right?

**Comment by faergeek** [comment]
You can save default behavior if you like it, but you could add some option so that it does not pipe it's output through `cssify` and just passes it to next transform, but what you suggest would be even better probably (I mean if it would behave that way by default) :+1: .

Would be cool if we could compose preprocessors for css in a more flexible way than now.

**Pull request merged**
