### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by faergeek**

### CODE REVIEW

**Comment by faergeek** [comment]
I would like to setup some code style using eslint, did you use it or something like jscs/jshint?

I just generally do not understand code style (2 or 4 spaces, space before `function` keyword and such things).

**Comment by faergeek** [comment]
Also what about using ES6 with Babel?

**Comment by davidguttman** [comment]
If we do code style it should be https://www.npmjs.com/package/standard

As for ES6 I'd prefer not to pull in Babel, so either use the node subset or stay with ES5.

**Comment by faergeek** [comment]
Almost done writing tests, take a look, please :-)

**Comment by davidguttman** [comment]
Looking way better!

Since we're now using ES6, be sure to set "engines" in `package.json`: https://docs.npmjs.com/files/package.json#engines

If you want to avoid using the private `tape` method to show coverage, we can just put that it in it's own "test" at the end called "coverage" or whatever. `tape` will make sure it runs after everything else.

One minor thing -- the [node convention is to use all lower case in file names](https://github.com/nodejs/node-v0.x-archive/issues/6000). So `lib/processCss.js` should be `lib/process-css.js`.

Nice work!

**Comment by faergeek** [comment]
I would like it to be compatible with Node 4, will test a little later.

About using private method, it's not just to collect coverage, we should close the window after running tests. Without explicit `window.close` it just leaves it open and process waits.

Will fix filenames a little later, Thanks! :+1:

**Comment by faergeek** [comment]
Fixed filenames and added "engines" field. Not sure what to do about "private" interface of tape.

**Comment by davidguttman** [comment]
Not a big deal, fine with using the private interface.

In `package.json` did you mean to do `"node" : ">= 4.0.0"` instead of `"npm" : ">= 4.0.0"`?

**Comment by faergeek** [comment]
Yes, sorry, will fix it right now

**Comment by faergeek** [comment]
Done

**Comment by faergeek** [comment]
It's probably better to squash some commits, right?

**Comment by davidguttman** [comment]
Probably, want me to wait on that?

**Comment by faergeek** [comment]
Done

**Comment by davidguttman** [comment]
Nice work!

**Comment by faergeek** [comment]
Thanks, I'm going to add support for css modules now :-)

**Pull request merged**
